// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlrfuajqspfmlbmvmlvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRscmZ1YWpxc3BmbWxibXZtbHZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NzMxODQsImV4cCI6MjA2NzI0OTE4NH0.z0bztTbqLHx_dP7QAqUMP0qJFCii7lt-iWy_TsUKr8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});